*** Settings ***

Documentation        Variáveis globais e configuração de ambiente


*** Variables ***

${email}            teste@gmail.com
${senha}            teste
${email_nok}        emailnok@gmail.com.br
${inv_email}        teste.com
${senha_nok}        senhanok
${csv_file_path}    C://Users//douglas.grangnano//Documents//Todos Movimentos_RAIZEN.csv
${txt_file_path}    C://Users//douglas.grangnano//Documents//77839_240215_3L.txt